# Generated by Django 4.2.19 on 2025-02-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moteldosguri', '0002_alter_clientes_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='horario',
            field=models.DateField(),
        ),
    ]
